# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://securified.net/"
theme="congo"

defaultContentLanguage = "en"

enableRobotsTXT = false
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]


#[[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY;"